// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

import type { D1Database } from '@cloudflare/workers-types'

declare global {
  interface CloudflareEnv {
    DB: D1Database
  }
}